### ISSUE TITLE
Printful API returns a 401 on valid api_key

### ISSUE THREAD

**Issue by andrewmarconi** [559Labs/django-dtg-store-manager#1]
## What was Expected?

API should return a response as described at https://www.theprintful.com/docs/files

## What Happened?

I receive a 401 Unauthorized error.

## How Can I Reproduce the issue?

```python
from vendor_printful import interface as pi
from vendor_printful import wrapper as pw

a = pw.PrintfulClient(Manufacturer.objects.get(code='P2'))

# This works without issue (so I know it's not the key).
the_products = a.get('products')

# This throws a 401 unauthorized error.
the_files = a.get('files')

# Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#  File "/code/vendor_printful/wrapper.py", line 48, in get
#    return self.__request('GET', path, params)
#  File "/code/vendor_printful/wrapper.py", line 112, in __request
#    raise PrintfulApiException(data['result'], data['code'])
# vendor_printful.wrapper.PrintfulApiException: 401 - Unauthorized
# 401 - Unauthorized
```

## At which commit was the issue noted?
https://github.com/559Labs/django-dtg-store-manager/commit/6d3d1f8a456f24d7f11150473b43e0489f2af707

## Relevant Libraries/Apps (if known)
* vendor_printful.wrapper, and downstream, vendor_printful.interface.

**Comment by andrewmarconi** [comment]
Silly error on my part. the API Key never actually encodes correctly. The Products call doesn't require the key, so it doesn't fail. However, since Files is tied to a specific store, if the key doesn't come in correctly, it will cause a 401 Authentication error. Need to redo the base64 encoding of the key.
